preprocess:
  do: False

train:
  train_frac: .8
  random_seed: 87
  gpus:
    - 1 
  max_epochs: 8
  batch_size: 16

seed: 87

model:
  _target_: src.model.DST
  d_model: 32
  n_blocks: 3
  n_heads: 8
  dropout: .1
  pad: -100