preprocess:
  do: False

train:
  train_frac: .8
  random_seed: 87
  gpus:
    - 1 
  max_epochs: 2
  batch_size: 32

seed: 87

model:
  _target_: src.model.DST
  d_model: 16
  n_blocks: 4
  n_heads: 8
  dropout: .1
  pad: -100