preprocess:
  do: False
  seed: 30


train:
  train_frac: .7
  val_frac: .15
  gpus:
    - 1 
  max_epochs: 3
  batch_size: 16
  causal: False
  seed: 87

model:
  _target_: "src.model.DST"
  d_model: 32
  n_blocks: 3
  n_heads: 8
  dropout: .1
  pad: -100
  dynamic: True
  lr: 0.001
  alpha: 0.01

hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}/${train.random_seed}
    subdir: ${hydra.job.num}