wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683386157.810262
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 7
      - 13
      - 23
      4: 3.10.11
      5: 0.15.2
      8:
      - 1
      - 5
      - 12
    m:
    - 1: trainer/global_step
      6:
      - 3
n_codes:
  desc: null
  value: 517
n_vitals:
  desc: null
  value: 25
n_demog:
  desc: null
  value: 2
d_model:
  desc: null
  value: 32
n_blocks:
  desc: null
  value: 3
n_heads:
  desc: null
  value: 8
dropout:
  desc: null
  value: 0.1
pad:
  desc: null
  value: -100
dynamic:
  desc: null
  value: true
causal:
  desc: null
  value: false
lr:
  desc: null
  value: 0.001
alpha:
  desc: null
  value: 0.01
